### ISSUE TITLE
Run.set_group behaviour with no_write flag

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/lyse#78]
There is potential unexpected behaviour with a call to `Run.set_group` if `no_write` was explicitly set to `True` when instantiating the `Run` object. This is consistent with the behaviour prior to #71, but is perhaps not consistent with the intention.

#72 fixed a bug with the implementation of #71, but using the `no_write=True` option at instantiation might mean that the code still raises an exception since the results group may not exist for the subgroup to be created in. #72 also modifies the file regardless of the `no_write` state.

#71 attempted to back up/restore the `no_write` flag state, but I'm not sure if this even made sense. Should `set_group()` mean that you intent to write to the file? Whatever behaviour we settle on, this method needs documenting!

**Comment by zakv** [comment]
Yeah you're right; calling `Run.set_group` will open the file and create the group regardless of `self.no_write`, which goes against what a user should expect from the `no_write` argument.

> Should set_group() mean that you intent to write to the file?

Right now `Run.group` is only used directly by `Run.save_result()` and `Run.save_results_array()` as the default hdf5 location to save results. Users are required to specify a group explicitly when using the `get` methods; `self.group` isn't used as a default there. Assuming that will remain to be true, I'd say yes, calling `Run.set_group()` should mean that you intend to write to the file.

> #71 attempted to back up/restore the no_write flag state, but I'm not sure if this even made sense.

I think you're talking about:
https://github.com/labscript-suite/lyse/blob/091044719c801972f62a78fc43e9ae22bd5d0461/lyse/__init__.py#L131-L132
and
https://github.com/labscript-suite/lyse/blob/091044719c801972f62a78fc43e9ae22bd5d0461/lyse/__init__.py#L152-L154

I think it does make sense actually, but there may be a better way to implement what it's trying to do. If you instantiate a `Run` instance from an interpreter with `no_write=False` then the attempt to set `self.group` in `Run.__init__()` fails since there isn't a lyse script running to name it after. Since there isn't a default group available, it sets `self.no_write=True` until a group is explicitly set so that the `save` methods don't get tripped up by the fact that they don't have a valid default save location. Once a default group is set with `set_group` it then restores `self.no_write` to `True` if the instance was instantiated that way so that the `save` methods work again.

The downside of that approach is that the `save` methods don't work before calling `set_group` even if you explicitly provide a value for their `group` argument. I think a slightly better approach would be to always have `self.no_write` set to whatever the user provided and set `self.group` to `None` if there isn't a script to name it after. Then the `save` methods can be updated to use the value passed for `group` if one is provided, and otherwise default to `self.group`. Then if `self.group` is `None` they can raise an error informing the user that they need to provide a value for the `group` argument or call `self.set_group()` to set a default value.

I also think it would be a good idea to have `Run._create_group_if_not_exists()` raise an error if the group doesn't already exist but `self.no_write` is `True`. That would be a good way to catch any other bugs like this that may crop up in the future.

Suggested changes:

* Make `Run._create_group_if_not_exists()` raise an error if the group doesn't already exist but `self.no_write` is `True`
* Ditch the usage of `self._no_group`'s to backup/restore `self.no_write`
  * Instead set `self.group` to `None` by default if there's no lyse script running to name it after, then set the `save` methods to raise an exception if they need `self.group` but it is `None`.
