### ISSUE TITLE
df.to_msgpack and pandas.read_msgpack removed from pandas

### ISSUE THREAD

**Issue by zakv** [labscript-suite/lyse#82]
Pandas [dropped support for msgpack](https://github.com/pandas-dev/pandas/issues/27722), I believe in the 0.25 to 1.0 transition judging by comparing different tagged versions [here](https://github.com/pandas-dev/pandas/blob/1.0.x/pandas/core/generic.py. ). Unfortunately this breaks lyse's "save dataframe" and "load dataframe" features.

Maybe it's best to switch to `df.to_pickle()` and `pandas.read_pickle()`? I don't see any good ways to support loading dataframes from old `msgpack` saves though, except maybe through some third party library.

**Comment by lakodarmstadt** [comment]
I think using pandas.to_parquet is an option. I tried pandas.to_feather first but this has difficulties with the multiindex structure of our dataframes. For pandas >=1.2 this is solved for pandas.to_parquet.
How can I set the requirement for pandas>=1.2? I can use the requirement textfile but this is only used during installation if I understand correctly.

**Comment by dihm** [comment]
Sorry for being very late to the party here, but I'm finally getting to grips with the issue here. I'm a little concerned about using parquet. I just tried to test #91. Not only does it require an optional dependency with lots of its own dependenices (pyarrow or fastparquet+numba), but the current pyarrow conda package is bugged and doesn't even work (you have to install via pip, see AnacondaRecipes/pyarrow-feedstock#2).

For now, I'm more inclined to use the pickle interface (with or without compression) as a more portable, working out of the box solution. Based on [this random blog post from years ago](http://matthewrocklin.com/blog/work/2015/03/16/Fast-Serialization), it seems pickle isn't that off in terms of performance either.

As for backwards compatibility, I'm not really sure what to do. There is a [third party package](https://github.com/TyberiusPrime/pandas-msgpack), but support seems extremely limited. Perhaps the best solution is to just not support loading old msgpacked files and telling the user to either manually convert to pickle (using 3rd party resources or an older version of pandas) or reload the source files and resave the dataframes as pickle files.

Does anyone have any thoughts?

**Comment by zakv** [comment]
Yeah I don't think there's a good way to handle this. Either we add a bunch of dependencies or we lose the ability to load old dataframes. My vote is to lose the ability to load old dataframes.

Maybe the call to `pandas.read_msgpack` can be left in a `try`/`except` block so that users who have an old version of pandas installed can still load dataframes saved the old way. The saving should now always call the new saving method though. That way a user could update their dataframe save format by opening then re-saving their dataframe using an up-to-date version of lyse in an environment with an old version of pandas.

As for parquet vs pickle, I agree that we should use pickle if using parquet requires adding dependencies. That's unfortunate given that lakodarmstadt was kind enough to put in the work to implement saving with parquet, but I think going with pickle instead is the right decision.

**Comment by philipstarkey** [comment]
I would be interested to know how well the `to_hdf` option worked in pandas....

Might get confusing having both HDF shot files and HDF data frame files (since we wouldn't want to save the data frame in an existing shot file), but having it human readable via HDFView might be beneficial and it's a format we could manually process ourselves should support be dropped like it was for msgpack. The biggest issue is probably whether it handles the multi-index properly (or any of the other weird thins we do with the data frame)

**Comment by dihm** [comment]
> Maybe the call to pandas.read_msgpack can be left in a try/except block so that users who have an old version of pandas installed can still load dataframes saved the old way. The saving should now always call the new saving method though. That way a user could update their dataframe save format by opening then re-saving their dataframe using an up-to-date version of lyse in an environment with an old version of pandas.

I do really like this method of maintaining some semblance of backwards compat, whichever method we end up using.

**Comment by philipstarkey** [comment]
Eugh. Requires pytables. Forget that idea then!

**Comment by dihm** [comment]
> Eugh. Requires pytables. Forget that idea then!

Glad to see I'm not alone in that opinion.

I'll go ahead and make a PR using pickle.

**Comment by lakodarmstadt** [comment]
Thanks for solving this.
